export const CONTINENT = [
  {
    title: "All",
    continent: "",
    color: "",
    background: "blue.50",
    colorscheme: "gray",
  },
  {
    title: "Asia",
    continent: "Asia",
    color: "white",
    background: "blue.100",
    colorscheme: "red",
  },
  {
    title: "Africa",
    continent: "Africa",
    color: "white",
    background: "blue.200",
    colorscheme: "pink",
  },
  {
    title: "Americas",
    continent: "Americas",
    color: "white",
    background: "blue.300",
    colorscheme: "purple",
  },
  {
    title: "Europe",
    continent: "Europe",
    color: "white",
    background: "blue.400",
    colorscheme: "blue",
  },
  {
    title: "Oceania",
    continent: "Oceania",
    color: "white",
    background: "blue.500",
    colorscheme: "teal",
  },
  {
    title: "Polar",
    continent: "Polar",
    color: "white",
    background: "blue.600",
    colorscheme: "green",
  },
];
